IF OBJECT_ID('silver.patients', 'U') IS NOT NULL
    DROP TABLE silver.patients;
GO

CREATE TABLE silver.patients(
    Id NVARCHAR(50),
    BIRTHDATE DATE,
    DEATHDATE DATE,
    FIRST NVARCHAR(50),
    LAST NVARCHAR(50),
    MARITAL_STATUS NVARCHAR(20),
    RACE NVARCHAR(50),
    ETHNICITY NVARCHAR(50),
    GENDER NVARCHAR(10),
    CITY NVARCHAR(50),
    STATE NVARCHAR(50),
    ZIP NVARCHAR(20),
    HEALTHCARE_EXPENSES FLOAT,
    HEALTHCARE_COVERAGE FLOAT,
    INCOME FLOAT,
    dwh_create_date DATETIME2(7) DEFAULT GETDATE()
);
GO

IF OBJECT_ID('silver.encounters', 'U') IS NOT NULL
    DROP TABLE silver.encounters;
GO

CREATE TABLE silver.encounters(
    Id NVARCHAR(50),
    START DATETIME2,
    STOP DATETIME2,
    PATIENT NVARCHAR(50),
    ORGANIZATION NVARCHAR(50),
    PAYER NVARCHAR(50),
    ENCOUNTERCLASS NVARCHAR(20),
    DESCRIPTION NVARCHAR(200),
    BASE_ENCOUNTER_COST FLOAT,
    TOTAL_CLAIM_COST FLOAT,
    PAYER_COVERAGE FLOAT,
    dwh_create_date DATETIME2(7) DEFAULT GETDATE()
);
GO

IF OBJECT_ID('silver.conditions', 'U') IS NOT NULL
    DROP TABLE silver.conditions;
GO

CREATE TABLE silver.conditions(
    START DATE,
    STOP DATE,
    PATIENT NVARCHAR(50),
    ENCOUNTER NVARCHAR(50),
    CODE NVARCHAR(50),
    DESCRIPTION NVARCHAR(200),
    dwh_create_date DATETIME2(7) DEFAULT GETDATE()
);
GO

IF OBJECT_ID('silver.organizations', 'U') IS NOT NULL
    DROP TABLE silver.organizations;
GO

CREATE TABLE silver.organizations(
    Id NVARCHAR(50),
    NAME NVARCHAR(200),
    CITY NVARCHAR(50),
    STATE NVARCHAR(50),
    ZIP NVARCHAR(20),
    UTILIZATION INT,
    dwh_create_date DATETIME2(7) DEFAULT GETDATE()
);
GO

IF OBJECT_ID('silver.payers', 'U') IS NOT NULL
    DROP TABLE silver.payers;
GO

CREATE TABLE silver.payers(
    Id NVARCHAR(50),
    NAME NVARCHAR(100),
    OWNERSHIP NVARCHAR(50),
    AMOUNT_COVERED FLOAT,
    AMOUNT_UNCOVERED FLOAT,
    COVERED_ENCOUNTERS INT,
    UNCOVERED_ENCOUNTERS INT,
    UNIQUE_CUSTOMERS INT,
    dwh_create_date DATETIME2(7) DEFAULT GETDATE()
);
GO