IF OBJECT_ID('bronze.patients', 'U') IS NOT NULL
    DROP TABLE bronze.patients;
GO

CREATE TABLE bronze.patients(
    Id NVARCHAR(50),
    BIRTHDATE DATE,
    DEATHDATE DATE,
    SSN NVARCHAR(20),
    DRIVERS NVARCHAR(20),
    PASSPORT NVARCHAR(20),
    PREFIX NVARCHAR(10),
    FIRST NVARCHAR(50),
    MIDDLE NVARCHAR(50),
    LAST NVARCHAR(50),
    SUFFIX NVARCHAR(10),
    MAIDEN NVARCHAR(50),
    MARITAL NVARCHAR(5),
    RACE NVARCHAR(50),
    ETHNICITY NVARCHAR(50),
    GENDER NVARCHAR(5),
    BIRTHPLACE NVARCHAR(100),
    ADDRESS NVARCHAR(100),
    CITY NVARCHAR(50),
    STATE NVARCHAR(50),
    COUNTY NVARCHAR(50),
    FIPS NVARCHAR(20),
    ZIP NVARCHAR(20),
    LAT FLOAT,
    LON FLOAT,
    HEALTHCARE_EXPENSES FLOAT,
    HEALTHCARE_COVERAGE FLOAT,
    INCOME FLOAT
);
GO

IF OBJECT_ID('bronze.encounters', 'U') IS NOT NULL
    DROP TABLE bronze.encounters;
GO

CREATE TABLE bronze.encounters(
    Id NVARCHAR(50),
    START DATETIME2,
    STOP DATETIME2,
    PATIENT NVARCHAR(50),
    ORGANIZATION NVARCHAR(50),
    PROVIDER NVARCHAR(50),
    PAYER NVARCHAR(50),
    ENCOUNTERCLASS NVARCHAR(50),
    CODE NVARCHAR(50),
    DESCRIPTION NVARCHAR(200),
    BASE_ENCOUNTER_COST FLOAT,
    TOTAL_CLAIM_COST FLOAT,
    PAYER_COVERAGE FLOAT,
    REASONCODE NVARCHAR(50),
    REASONDESCRIPTION NVARCHAR(200)
);
GO

IF OBJECT_ID('bronze.conditions', 'U') IS NOT NULL
    DROP TABLE bronze.conditions;
GO

CREATE TABLE bronze.conditions(
    START DATE,
    STOP DATE,
    PATIENT NVARCHAR(50),
    ENCOUNTER NVARCHAR(50),
    SYSTEM NVARCHAR(100),
    CODE NVARCHAR(50),
    DESCRIPTION NVARCHAR(200)
);
GO

IF OBJECT_ID('bronze.organizations', 'U') IS NOT NULL
    DROP TABLE bronze.organizations;
GO

CREATE TABLE bronze.organizations(
    Id NVARCHAR(50),
    NAME NVARCHAR(200),
    ADDRESS NVARCHAR(200),
    CITY NVARCHAR(50),
    STATE NVARCHAR(50),
    ZIP NVARCHAR(20),
    LAT FLOAT,
    LON FLOAT,
    PHONE NVARCHAR(50),
    REVENUE FLOAT,
    UTILIZATION INT
);
GO

IF OBJECT_ID('bronze.payers', 'U') IS NOT NULL
    DROP TABLE bronze.payers;
GO

CREATE TABLE bronze.payers(
    Id NVARCHAR(50),
    NAME NVARCHAR(100),
    OWNERSHIP NVARCHAR(50),
    ADDRESS NVARCHAR(200),
    CITY NVARCHAR(50),
    STATE_HEADQUARTERED NVARCHAR(50),
    ZIP NVARCHAR(20),
    PHONE NVARCHAR(50),
    AMOUNT_COVERED FLOAT,
    AMOUNT_UNCOVERED FLOAT,
    REVENUE FLOAT,
    COVERED_ENCOUNTERS INT,
    UNCOVERED_ENCOUNTERS INT,
    COVERED_MEDICATIONS INT,
    UNCOVERED_MEDICATIONS INT,
    COVERED_PROCEDURES INT,
    UNCOVERED_PROCEDURES INT,
    COVERED_IMMUNIZATIONS INT,
    UNCOVERED_IMMUNIZATIONS INT,
    UNIQUE_CUSTOMERS INT,
    QOLS_AVG FLOAT,
    MEMBER_MONTHS INT
);
GO